### ISSUE TITLE
get_fourfactors (index out of range error) 

### ISSUE THREAD

**Issue by Joshimmor** [j-andrews7/kenpompy#15] opened 2022-04-04 00:48 UTC
When making a get_fourfactors call, a list index out of range error was returned. I used this library before, I don't know how to trace this bug.

**Comment by esqew** [comment] 2022-07-22 14:08
I only get this when my login fails; otherwise I can't reproduce this. Can you verify your credentials, then run this small script and see what happens?

```
from kenpompy.utils import login
from kenpompy.summary import get_fourfactors

browser = login(r'<my_email>', r'<my_password>')
print(get_fourfactors(browser, 2022))
```

**Comment by j-andrews7** [comment] 2022-08-03 21:50
Yeah, I can't replicate this, likely due to not logging in. Closing, but feel free to re-open if it's still a problem.

**Closed by j-andrews7** 2022-08-03 21:50 UTC
